import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import slidesRouter from "./slides";
import servicesRouter from "./services";
import containersRouter from "./containers";
import valuesRouter from "./values";
import testimonialsRouter from "./testimonials";
import partnersRouter from "./partners";
import serviceRequestsRouter from "./serviceRequests";
import conversationsRouter from "./conversations";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import aiChatRouter from "./aiChat";
import settingsRouter from "./settings";
import uploadsRouter from "./uploads";
import sitemapRouter from "./sitemap";
import adsRouter from "./ads";
import analyticsRouter from "./analytics";
import aiSeoRouter from "./aiSeo";
import postsRouter from "./posts";
import employeesRouter from "./employees";
import databaseRouter from "./database";
import whatsappRouter from "./whatsapp";
import pushRouter from "./push";
import seoPagesRouter from "./seoPages";
import reviewsRouter from "./reviews";
import containerSystemRouter from "./containerSystem";
import hostingerDeployRouter from "./hostingerDeploy";
import seoMetricsRouter from "./seoMetrics";
import structuredContentRouter from "./structuredContent";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(slidesRouter);
router.use(servicesRouter);
router.use(containersRouter);
router.use(valuesRouter);
router.use(testimonialsRouter);
router.use(partnersRouter);
router.use(serviceRequestsRouter);
router.use(conversationsRouter);
router.use(notificationsRouter);
router.use(adminRouter);
router.use(aiChatRouter);
router.use(settingsRouter);
router.use(uploadsRouter);
router.use(sitemapRouter);
router.use(adsRouter);
router.use(analyticsRouter);
router.use(aiSeoRouter);
router.use(postsRouter);
router.use(employeesRouter);
router.use(databaseRouter);
router.use(whatsappRouter);
router.use(pushRouter);
router.use(seoPagesRouter);
router.use(reviewsRouter);
router.use(containerSystemRouter);
router.use(hostingerDeployRouter);
router.use(seoMetricsRouter);
router.use(structuredContentRouter);

export default router;
